= Spring REST Docs (사전과제 2번 - 광고플랫폼 구축)
이상현(6045)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // TOC(Table Of Contents)를 문서의 좌측에 위치
:toclevels: 2
:sectlinks:

[[Product-API]]
== 상품(Product) 도메인

[[상품-정보-리스트-등록]]
=== 상품 정보 리스트 등록
operation::POST_api-products[snippets='http-request,request-fields,http-response,response-fields']

[[상품-정보-리스트-등록-유효성-검사]]
=== 상품 정보 리스트 등록 유효성 검사
operation::POST_api-products-validation[snippets='http-request,request-fields,http-response,response-fields']

[[상품-정보-리스트-조회]]
=== 상품 정보 리스트 조회
operation::GET_api-products[snippets='http-request,http-response,response-fields']

[[Company-API]]
== 업체(Company) 도메인

[[업체-등록]]
=== 업체 등록
operation::POST_api-company-register[snippets='http-request,request-fields,http-response,response-fields']

[[업체-등록-유효성-검사]]
=== 업체 등록 유효성 검사
operation::POST_api-company-validation[snippets='http-request,request-fields,http-response,response-fields']

[[업체-정보-리스트-조회]]
=== 업체 정보 리스트 조회
operation::GET_api-companies[snippets='http-request,http-response,response-fields']

[[Contract-API]]
== 계약(Contract) 도메인

[[계약-생성]]
=== 계약 생성
operation::POST_api-contract-create[snippets='http-request,request-fields,http-response,response-fields']

[[계약-생성-유효성-검사]]
=== 계약 생성 유효성 검사
operation::POST_api-contract-validation[snippets='http-request,request-fields,http-response,response-fields']

[[계약-리스트-조회]]
=== 계약 리스트 조회
operation::GET_api-contracts[snippets='http-request,http-response,response-fields']

[[AdBid-API]]
== 광고입찰(AD Bid) 도메인

[[광고입찰-생성]]
=== 광고입찰 생성
operation::POST_api-adbid-create[snippets='http-request,request-fields,http-response,response-fields']

[[광고입찰-유효성-검사]]
=== 광고입찰 유효성 검사
operation::POST_api-adbid-validation[snippets='http-request,request-fields,http-response,response-fields']
