= Spring REST Docs - 광고플랫폼 구축
이상현(dev.maemi@gmail.com, 6045)
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // TOC(Table Of Contents)를 문서의 좌측에 위치
:toclevels: 2
:sectlinks:

[[Product-API]]
== 상품(Product) 도메인

[[상품정보-리스트-생성]]
=== 상품 정보 리스트 생성
operation::POST_api-products[snippets='http-request,request-fields,http-response,response-fields']

[[상품정보-리스트-생성-시-유효성-검사]]
=== 상품 정보 리스트 등록 유효성 검사
operation::POST_api-products-validation[snippets='http-request,request-fields,http-response,response-fields']

[[상품정보-리스트-조회]]
=== 상품 정보 리스트 조회
operation::GET_api-products[snippets='http-request,http-response,response-fields']

[[Company-API]]
== 업체(Company) 도메인

[[업체-등록]]
=== 업체 등록
operation::POST_api-company-register[snippets='http-request,request-fields,http-response,response-fields']

[[업체-등록-시-유효성-검사]]
=== 업체 등록 시 유효성 검사
operation::POST_api-company-validation[snippets='http-request,request-fields,http-response,response-fields']

[[업체정보-리스트-조회]]
=== 업체정보 리스트 조회
operation::GET_api-companies[snippets='http-request,http-response,response-fields']

[[업체정보-중-업체명을-제외한-채-수정]]
=== 업체정보 중 업체명을 제외한 채 수정
operation::POST_api-company-update[snippets='http-request,request-fields,http-response,response-fields']

[[Contract-API]]
== 계약(Contract) 도메인

[[계약-생성]]
=== 계약 생성
operation::POST_api-contract-create[snippets='http-request,request-fields,http-response,response-fields']

[[계약-생성-유효성-검사-1]]
=== 계약 생성 유효성 검사 1
operation::POST_api-contract-validation1[snippets='http-request,request-fields,http-response,response-fields']

[[계약-생성-유효성-검사-2]]
=== 계약 생성 유효성 검사 2
operation::POST_api-contract-validation2[snippets='http-request,request-fields,http-response,response-fields']

[[계약-리스트-조회]]
=== 계약 리스트 조회
operation::GET_api-contracts[snippets='http-request,http-response,response-fields']

[[AdBid-API]]
== 광고입찰(AD Bid) 도메인

[[광고입찰-생성-1]]
=== 광고입찰 생성 1
operation::POST_api-ad-bid-create1[snippets='http-request,request-fields,http-response,response-fields']

[[광고입찰-생성-2]]
=== 광고입찰 생성 2
operation::POST_api-ad-bid-create2[snippets='http-request,request-fields,http-response,response-fields']

[[광고입찰-생성-3]]
=== 광고입찰 생성 3
operation::POST_api-ad-bid-create3[snippets='http-request,request-fields,http-response,response-fields']

[[광고입찰-생성-시-유효성-검사]]
=== 광고입찰 생성 시 유효성 검사
operation::POST_api-ad-bid-validation[snippets='http-request,request-fields,http-response,response-fields']

[[AdDisplay-API]]
== 광고전시(AD Display) 도메인

[[광고전시-리스트-조회]]
=== 광고전시 리스트 조회
operation::GET_api-ad-display[snippets='http-request,http-response,response-fields']

[[AdCharge-API]]
== 광고과금(AD Charge) 도메인

[[광고과금-생성-1]]
=== 광고과금 생성 1
operation::POST_api-ad-charge-create1[snippets='http-request,request-fields,http-response,response-fields']

[[광고과금-생성-2]]
=== 광고과금 생성 2
operation::POST_api-ad-charge-create2[snippets='http-request,request-fields,http-response,response-fields']

[[광고과금-생성-3]]
=== 광고과금 생성 3
operation::POST_api-ad-charge-create3[snippets='http-request,request-fields,http-response,response-fields']

[[광고과금-생성-4]]
=== 광고과금 생성 4
operation::POST_api-ad-charge-create4[snippets='http-request,request-fields,http-response,response-fields']

[[광고과금-유효성-검사]]
=== 광고과금 유효성 검사
operation::POST_api-ad-charge-validation[snippets='http-request,request-fields,http-response,response-fields']

[[AdChargeCal-API]]
== 광고과금정산(AD Charge Calculation) 도메인

[[광고과금정산-결과-리스트-조회]]
=== 광고과금정산 결과 리스트 조회
operation::GET_api-ad-charge-cals[snippets='http-request,http-response,response-fields']
